package com.example.madrona_rapidrecall

/**
 * Stores key information about a user's attempt
 *
 * Most of its parameters are recorded at the GameScreen.kt for direct access
 * of values needed for its parameters. A new object of this class is generated
 * per user attempt. The decision for not setting its parameters as private is
 * because they do not contain any sensitive information and is not really
 * accessed anywhere other than for display in LogScreen.kt
 *
 * @param seqLength: the sequence length inputted by the user
 * @param input: the user's guess of the generated sequence
 * @param sequence: the actual sequence generated by the Recall class
 * @param timestamp: The timestamp of the user when the attempt occurred
 * @param check: the result of the attempt
 */
class Attempt(
    val seqLength: Int,
    val input: List<Int>,
    val sequence: List<Int>,
    val timestamp: String,
    val check: String) {
}